import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.scss";
import Navbar from "@/components/navbar/navbar.component";
import Providers from "./providers";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

const arima = localFont({
  src: [
    {
      path: "../public/fonts/ArimaMadurai-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-arima",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <body className={arima.className}>
        <Navbar />
        <Providers>
          {children}
          <Analytics />
        </Providers>
      </body>
    </html>
  );
}
